# V3 - 修正執行的 Python 腳本檔案名稱
name: Scheduled Stock Prediction

on:
  workflow_dispatch:
  schedule:
    # 規則一：盤中執行
    # - cron: '*/15 13-20 * * 1-5'

    # 規則二：收盤後複盤執行
    - cron: '30 20 * * 1-5' # 夏令時的收盤後複盤
    - cron: '30 21 * * 1-5' # 冬令時的收盤後複盤

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # 確保安裝了假日檢查所需的套件
          pip install pandas_market_calendars

      - name: Run LIVE prediction script
        # === 關鍵修正 ===
        # 將執行的腳本名稱從 run_prediction.py 改為 live_predict.py，以匹配您倉庫中的實際檔案
        run: python live_predict.py
